### ISSUE TITLE
Missing @Component or @Configuration on class

### ISSUE THREAD

**Issue by oneturkmen** [daggerok/streaming-file-server#52]
The following class uses `@Bean` on a field, but is missing `@Component` or `@Configuration` annotation on the class. Also, class uses `@Order` which requires `@Component` on the same class (directly or indirectly). Is it intentional?

https://github.com/daggerok/streaming-file-server/blob/dea9b5a1cbd84580d15eacd92039979ac364e210/modules/apps/file-items-service/src/main/java/daggerok/config/CorsWebFluxCfg.java#L11

Reference: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Bean.html

**Comment by daggerok** [comment]
Hello, sorry for late response. Yes annotation is missing simply to disable that config completely
